services:
  - type: web
    name: costumbres-mercantiles
    env: python
    runtime: python-3.11.9
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.9"