services:
  - type: web
    name: costumbres-mercantiles
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: RENDER
        value: "true"